conditioning:
  method: ps
  params:
    scale: 1.5 #0.5 it depend on the image range

data:
  name: ffhq
  root: ./data/SR_image/
  #root: ./data/one_image/
measurement:
  operator:
    name: noise
#   mask_opt:
#     mask_type: box
#     #mask_len_range: !!python/tuple [128, 129]  # for box
#     mask_len_range: !!python/tuple [101, 102]  # for box
#     #mask_prob_range: !!python/tuple [0.3, 0.7]  # for random
#    image_size: 320


  noise:
    name: gaussian
    sigma: 0.25
