conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: ./data/demo_HDR/

measurement:
  operator:
    name: high_dynamic_range
    scale: 2
  
  noise: 
    name: gaussian
    sigma: 0.05
