conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: ./data/demo_baby/

measurement:
  operator:
    name: motion_blur
    kernel_size: 61
    intensity: 0.5

  noise: 
    name: gaussian
    sigma: 0.00
